CREATE TABLE [GameCategory] (
	Id int NOT NULL,
	Name string NOT NULL,
	GameId int NOT NULL,
  CONSTRAINT [PK_GAMECATEGORY] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Game] (
	Id int NOT NULL,
	Name string NOT NULL,
	Price decimal NOT NULL,
	Description string NOT NULL,
	CategoryId int NOT NULL,
	ImagePath string NOT NULL,
	IsDeleted boolean NOT NULL,
	CartId int NOT NULL,
  CONSTRAINT [PK_GAME] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [User] (
	Id int NOT NULL,
	FirstName string NOT NULL,
	LastName string NOT NULL,
	Email string NOT NULL,
	Password string NOT NULL,
	AvatarPath string NOT NULL,
	CartId int NOT NULL,
	CommentId int NOT NULL,
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Comment] (
	Id int NOT NULL,
	Body string NOT NULL,
	CommentedTime datetime NOT NULL,
	IsDeleted boolean NOT NULL,
	IsReplied boolean NOT NULL,
	UserId int NOT NULL,
	GameId int NOT NULL,
	RepliedCommentId int NOT NULL,
  CONSTRAINT [PK_COMMENT] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Cart] (
	Id int NOT NULL,
	UserId int NOT NULL,
	ReciptId int NOT NULL,
  CONSTRAINT [PK_CART] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Receipt] (
	Id int NOT NULL,
	Quantity int NOT NULL,
	GameId int NOT NULL,
	CartId int NOT NULL,
  CONSTRAINT [PK_RECEIPT] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [Order] (
	Id int NOT NULL,
	UserId int NOT NULL,
	PaymentType int NOT NULL,
	Comments string,
	Confirmed boolean NOT NULL,
	TotalPrice decimal NOT NULL,
	CartId int NOT NULL,
  CONSTRAINT [PK_ORDER] PRIMARY KEY CLUSTERED
  (
  [Id] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
ALTER TABLE [GameCategory] WITH CHECK ADD CONSTRAINT [GameCategory_fk0] FOREIGN KEY ([GameId]) REFERENCES [Game]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [GameCategory] CHECK CONSTRAINT [GameCategory_fk0]
GO

ALTER TABLE [Game] WITH CHECK ADD CONSTRAINT [Game_fk0] FOREIGN KEY ([CategoryId]) REFERENCES [GameCategory]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Game] CHECK CONSTRAINT [Game_fk0]
GO
ALTER TABLE [Game] WITH CHECK ADD CONSTRAINT [Game_fk1] FOREIGN KEY ([CartId]) REFERENCES [Cart]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Game] CHECK CONSTRAINT [Game_fk1]
GO

ALTER TABLE [User] WITH CHECK ADD CONSTRAINT [User_fk0] FOREIGN KEY ([CartId]) REFERENCES [Cart]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [User] CHECK CONSTRAINT [User_fk0]
GO
ALTER TABLE [User] WITH CHECK ADD CONSTRAINT [User_fk1] FOREIGN KEY ([CommentId]) REFERENCES [Comment]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [User] CHECK CONSTRAINT [User_fk1]
GO

ALTER TABLE [Comment] WITH CHECK ADD CONSTRAINT [Comment_fk0] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Comment] CHECK CONSTRAINT [Comment_fk0]
GO
ALTER TABLE [Comment] WITH CHECK ADD CONSTRAINT [Comment_fk1] FOREIGN KEY ([GameId]) REFERENCES [Game]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Comment] CHECK CONSTRAINT [Comment_fk1]
GO
ALTER TABLE [Comment] WITH CHECK ADD CONSTRAINT [Comment_fk2] FOREIGN KEY ([RepliedCommentId]) REFERENCES [Comment]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Comment] CHECK CONSTRAINT [Comment_fk2]
GO

ALTER TABLE [Cart] WITH CHECK ADD CONSTRAINT [Cart_fk0] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Cart] CHECK CONSTRAINT [Cart_fk0]
GO
ALTER TABLE [Cart] WITH CHECK ADD CONSTRAINT [Cart_fk1] FOREIGN KEY ([ReciptId]) REFERENCES [Receipt]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Cart] CHECK CONSTRAINT [Cart_fk1]
GO

ALTER TABLE [Receipt] WITH CHECK ADD CONSTRAINT [Receipt_fk0] FOREIGN KEY ([GameId]) REFERENCES [Game]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Receipt] CHECK CONSTRAINT [Receipt_fk0]
GO
ALTER TABLE [Receipt] WITH CHECK ADD CONSTRAINT [Receipt_fk1] FOREIGN KEY ([CartId]) REFERENCES [Cart]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Receipt] CHECK CONSTRAINT [Receipt_fk1]
GO

ALTER TABLE [Order] WITH CHECK ADD CONSTRAINT [Order_fk0] FOREIGN KEY ([UserId]) REFERENCES [User]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Order] CHECK CONSTRAINT [Order_fk0]
GO
ALTER TABLE [Order] WITH CHECK ADD CONSTRAINT [Order_fk1] FOREIGN KEY ([CartId]) REFERENCES [Cart]([Id])
ON UPDATE CASCADE
GO
ALTER TABLE [Order] CHECK CONSTRAINT [Order_fk1]
GO

